"""empty message

Revision ID: 3ff798bd324c
Revises: 
Create Date: 2023-04-24 15:40:40.556772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff798bd324c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_tag', sa.String(length=50), nullable=False),
    sa.Column('number_plate', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_plate'),
    sa.UniqueConstraint('rfid_tag')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('number_plate', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['number_plate'], ['vehicle.number_plate'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cnic', sa.String(length=50), nullable=False),
    sa.Column('engine_number', sa.String(length=50), nullable=False),
    sa.Column('number_plate', sa.String(length=50), nullable=True),
    sa.Column('rfid_tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['number_plate'], ['vehicle.number_plate'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('rfid_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_table('location')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
